### ISSUE TITLE
fix: pnpm-lock.yamlが壊れている

### ISSUE THREAD

**Issue by tufusa** [mct-joken/mct-student-association#17]
- react-responsiveがimportできない
- pnpm iに失敗する
` ERROR  /css-mediaquery@0.1.2 is an invalid relative dependency path`

#### 経緯
- 元々のlockfileVersionが5.4だった
- 誰かが新しくpnpm諸々を入れる
- lockfileVersionが最新の6にされる
- それが流れてきて私のlockfileVersionが6になる
- feat/css(バージョン6)をmain(バージョン5.4)にマージする
- 大部分はコンフリクト解決に巻き込まれ直った
- 一部が残り、バージョン6の記法がバージョン5.4の環境で読み込めない

多分パッケージ名とバージョンの区切りが`@`なのがまずいので`/`にすれば直る

**Comment by laminne** [comment]
Resolved #18
