### ISSUE TITLE
fix: bodyにmax-widthを設定する

### ISSUE THREAD

**Issue by laminne** [mct-joken/mct-student-association#27]
画面サイズが大きいと間伸び(?)するのでmax-widthを設定した方が見やすい気がします
![スクリーンショット 2023-05-24 15 21 59](https://github.com/mct-joken/mct-student-association/assets/40442980/1d0b3506-c40a-4db7-b1ee-e56714298487)

**Comment by kiji-haru** [comment]
最大1000pxくらい?

**Comment by laminne** [comment]
多分それくらいで良いと思う

**Comment by laminne** [comment]
Resolved #31
