### ISSUE TITLE
fix:学生会メンバーページの情報の追加

### ISSUE THREAD

**Issue by Suzune2741** [mct-joken/mct-student-association#28]
学生会メンバーで局長、副局長は表示されているが、執行部の情報が存在していないので追加したほうがいいと思います。

**Comment by kiji-haru** [comment]
執行部の情報まだないから待って

**Comment by kiji-haru** [comment]
会長補佐：角知樹

副会長補佐：石原大雅

議長：福島日向

副議長：永吉琉人

だそうです。それじゃよろしく
