### ISSUE TITLE
fix: 画面幅が 600px < width < 800px の際にメニューが閉じない

### ISSUE THREAD

**Issue by tufusa** [mct-joken/mct-student-association#34]
画面幅が 600px < width < 800pxだとメニューを開いてリンクを踏んでもメニューが閉じない
ヘッダのブレークポイント(800px)とフッタのブレークポイント(600px)が違うせい

ブレークポイントをそろえるかWideFooterにもメニューを閉じる処理をつけるかする

**Comment by laminne** [comment]
Resolved #35
