### ISSUE TITLE
fix: 部活動・メンバーページでブラウザにWarningが出る

### ISSUE THREAD

**Issue by tufusa** [mct-joken/mct-student-association#36]
![image](https://github.com/mct-joken/mct-student-association/assets/77904659/ee6db07c-e75d-4956-8338-c5cc0cd77234)
map使うときはkeyプロパティをつけないと怒られる

**Comment by kiji-haru** [comment]
了解。他にも使ってたかも

**Comment by laminne** [comment]
Fixed at #39
