### ISSUE TITLE
feat: 各部のSNSリンクの追加

### ISSUE THREAD

**Issue by laminne** [mct-joken/mct-student-association#40]
現状把握できてる分だけ
- 囲碁将棋部
  - [Twitter](https://twitter.com/MCTIgoShogi)
  - [Instagram](https://instagram.com/mct_shogi_club)
- 写真部
  - [Instagram](https://instagram.com/mct.photos)
  - [Twitter](https://twitter.com/mct_shashinbu)
- 卓球部
  - [Instagram](https://instagram.com/mct.tabletennis)
- クイズ研究会
  - [Instagram](https://instagram.com/mctquiz)
  - [Twitter](https://twitter.com/MCT_Quiz)
- 吹奏楽部
  - [Twitter](https://twitter.com/mctbb_prm)
  - [Instagram](https://instagram.com/mct_windclub)
- サッカー部
  - [Twitter](https://twitter.com/mct_football)
- レスコン
  - [Twitter](https://twitter.com/MCTrescon)
- ラグビー部
  - [Instagram](https://instagram.com/matsue_rugby)
- ロボコン
  - [Twitter](https://twitter.com/Matsue_Robocon)
- 郷土研究部
  - [Instagram](https://instagram.com/mct.kyodo_club)
- 水泳部
  - [Twitter](https://twitter.com/matsue_ct_swim)
- エコラン
  - [Twitter](https://twitter.com/mct_ecorun)
- ボート部
  - [Instagram](https://instagram.com/mctrt_official)
- 漫画研究会
  - [Twitter](https://twitter.com/manken_mct)
- 女子バスケットボール部
  - [Instagram](https://instagram.com/mct_jbas)
- デザコン
  - [Twitter](https://twitter.com/mct_dezakon)
- ハンドボール部
  - [Instagram](https://instagram.com/mct.handball)

**Comment by kiji-haru** [comment]
ついでに運動部と文化部分けるか

**Comment by laminne** [comment]
体育局/文化局表記の方がいいかも

**Comment by kiji-haru** [comment]
なるほど。ちなみにロボコンやレスコンとか後うちは文化局が管轄してるの？

**Comment by laminne** [comment]
うち(情研)は文化局なんだけど、〇〇コン関連は確かどこでもないからどうしようか(別に運動部/文化部でもいい気がしてきた

**Comment by kiji-haru** [comment]
じゃあ取り敢えずそうするか

**Comment by laminne** [comment]
よろしく頼んだ
