### ISSUE TITLE
fix(ui): 部活一覧ページのソーシャルアイコンの不自然な空白を消す

### ISSUE THREAD

**Issue by laminne** [mct-joken/mct-student-association#42]

**Comment by tufusa** [comment]
![image](https://github.com/mct-joken/mct-student-association/assets/77904659/62654b1a-0b40-4b2f-ba76-bf5524354ddf)
適当につついてみたけどこういう話？

**Comment by kiji-haru** [comment]
良さげな気がする

**Comment by laminne** [comment]
> ![image](https://github.com/mct-joken/mct-student-association/assets/77904659/62654b1a-0b40-4b2f-ba76-bf5524354ddf)
> 
> 適当につついてみたけどこういう話？

そういうこと
