### ISSUE TITLE
fix:firefoxでヘッダーのレイアウトが崩れる

### ISSUE THREAD

**Issue by kiharu3112** [mct-joken/mct-student-association#58]
![Screenshot 2023-06-15 at 9 55 17](https://github.com/mct-joken/mct-student-association/assets/74781355/4dcc5875-4aef-49b4-85a2-762996f38b09)

検証頼む

**Comment by kiji-haru** [comment]
間違えた

**Comment by tufusa** [comment]
確認できなかった

Chrome
![image](https://github.com/mct-joken/mct-student-association/assets/77904659/1b2e8a1b-30b0-46e2-8490-34498ce00748)

Edge
![image](https://github.com/mct-joken/mct-student-association/assets/77904659/89787f2c-636a-4980-a6c3-2b8545c6c32a)

Firefox
![image](https://github.com/mct-joken/mct-student-association/assets/77904659/e4e67b32-fe79-4992-ac9f-71ddc80de14b)

**Comment by tufusa** [comment]
そっちの画像のフォントが変な気がする

**Comment by kiji-haru** [comment]
なるほど。じゃあとりま大丈夫な感じね
